### ISSUE TITLE
[BUG] Can't use numeric categorical features in some DL models

### ISSUE THREAD

**Issue by alex-hse-repository** [etna-team/etna#283]
### 🐛 Bug Report

We can't use use numeric categorical features like OHE(Segment) in `MLPModel`, `RNNModel`, `PatchTSModel`, `DeepARNativeModel` as we filter columns in `make_samples` like this
```
values_real = df.select_dtypes(include=[np.number]).values
```

### Expected behavior

We can use numeric categorical features in all DL models

### Code
```
from etna.datasets import TSDataset
from etna.models.nn import MLPModel
from etna.transforms import SegmentEncoderTransform, FilterFeaturesTransform, OneHotEncoderTransform
HORIZON = 7

original_df = pd.read_csv("data/example_dataset.csv")
df = TSDataset.to_dataset(original_df)
ts = TSDataset(df, freq="D")

model = MLPModel(
    input_size=4,
    hidden_size=[10],
    encoder_length=14,
    decoder_length=14,
)

pipeline = Pipeline(
    model=model,
    transforms=[
        SegmentEncoderTransform(),
        OneHotEncoderTransform(in_column="segment_code"),
        FilterFeaturesTransform(exclude=["segment_code"])
    ],
    horizon=HORIZON

)

pipeline.fit(ts)
```

```

RuntimeError: mat1 and mat2 shapes cannot be multiplied (224x0 and 4x10)
```

### Checklist

- [X] Bug appears at the latest library version

**Comment by egoriyaa** [comment]
Originally `PatchTSModel` doesn't work with additional features. But it isn't clarified properly now, so we have [bug issue](https://github.com/etna-team/etna/issues/345) for this. We want to add a support of additional features in future - [issue](https://github.com/etna-team/etna/issues/343).

For other models your issue was fixed by #352. Also you can use categorical features in `nn` models - added in #344.
